#!/usr/bin/env python3
"""Compile data/library.yml → library-data.js + cache-busted script include."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.stderr.write("PyYAML required: pip install pyyaml\n")
    sys.exit(1)

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "data" / "library.yml"
JS_UI = ROOT / "styles" / "library.js"
OUT_DATA = ROOT / "styles" / "library-data.js"
OUT_INCLUDE = ROOT / "styles" / "library-scripts.html"

DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def parse_date(value, *, field: str, title: str) -> str | None:
    if value is None or value == "":
        return None
    if isinstance(value, date):
        return value.isoformat()
    text = str(value).strip()
    if not DATE_RE.match(text):
        sys.stderr.write(
            f"library.yml: '{title}' {field} must be YYYY-MM-DD (got {value!r})\n"
        )
        sys.exit(1)
    # Validate calendar date
    try:
        date.fromisoformat(text)
    except ValueError:
        sys.stderr.write(f"library.yml: '{title}' {field} is not a valid date\n")
        sys.exit(1)
    return text


def main() -> None:
    data = yaml.safe_load(SRC.read_text(encoding="utf-8")) or {}
    books = data.get("books") or []
    if not isinstance(books, list):
        sys.stderr.write("library.yml: 'books' must be a list\n")
        sys.exit(1)

    cleaned = []
    for i, raw in enumerate(books):
        if not isinstance(raw, dict):
            sys.stderr.write(f"library.yml: book #{i + 1} must be a mapping\n")
            sys.exit(1)
        title = str(raw.get("title") or "").strip()
        if not title:
            sys.stderr.write(f"library.yml: book #{i + 1} needs a title\n")
            sys.exit(1)
        try:
            page = int(raw.get("page", 0))
            pages = int(raw.get("pages", 0))
        except (TypeError, ValueError):
            sys.stderr.write(f"library.yml: '{title}' needs integer page/pages\n")
            sys.exit(1)
        if pages <= 0:
            sys.stderr.write(f"library.yml: '{title}' needs pages > 0\n")
            sys.exit(1)
        page = max(0, min(page, pages))
        added = parse_date(raw.get("added"), field="added", title=title)
        finished = parse_date(raw.get("finished"), field="finished", title=title)
        if page >= pages and not finished:
            sys.stderr.write(
                f"library.yml: '{title}' is finished (page >= pages) but has no finished: date\n"
            )
            sys.exit(1)
        if finished and not added:
            sys.stderr.write(
                f"library.yml: '{title}' has finished but no added: date\n"
            )
            sys.exit(1)
        if added and finished and finished < added:
            sys.stderr.write(
                f"library.yml: '{title}' finished is before added\n"
            )
            sys.exit(1)

        cleaned.append(
            {
                "title": title,
                "author": str(raw.get("author") or "").strip(),
                "category": str(raw.get("category") or "other").strip().lower(),
                "page": page,
                "pages": pages,
                "added": added,
                "finished": finished,
            }
        )

    payload = json.dumps({"books": cleaned}, ensure_ascii=False, indent=2)
    data_js = (
        f"/* Generated from data/library.yml — do not edit by hand. */\n"
        f"window.LIBRARY = {payload};\n"
    )
    OUT_DATA.write_text(data_js, encoding="utf-8")

    ui = JS_UI.read_text(encoding="utf-8") if JS_UI.exists() else ""
    bust = hashlib.sha1((data_js + ui).encode("utf-8")).hexdigest()[:10]
    OUT_INCLUDE.write_text(
        f"<!-- Generated by scripts/sync_library.py — do not edit by hand. -->\n"
        f'<script src="styles/library-data.js?v={bust}"></script>\n'
        f'<script src="styles/library.js?v={bust}"></script>\n',
        encoding="utf-8",
    )
    print(
        f"Wrote {OUT_DATA.relative_to(ROOT)} ({len(cleaned)} books), "
        f"{OUT_INCLUDE.relative_to(ROOT)} (v={bust})"
    )


if __name__ == "__main__":
    main()
